# Generated by Django 4.2.1 on 2023-07-20 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='expire_date',
            new_name='expiry_date',
        ),
    ]
