# Generated by Django 4.2.1 on 2023-05-28 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='cat_image',
        ),
    ]
